"""
YouTube upload and analytics service for AutoCourse Studio.
Integrates with youtube_auth and youtube_scheduler.
"""
from __future__ import annotations
import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from backend.core.config import project_root
from backend.core.job_store import get_job, list_jobs, update_job
from backend.services.youtube_auth import get_authenticated_service, get_channel_profile, is_authenticated
from backend.services.youtube_optimizer import extract_video_thumbnail, optimize_metadata
from backend.services.youtube_scheduler import schedule_upload


def upload_video_to_youtube(
    job_id: str,
    title: Optional[str] = None,
    description: Optional[str] = None,
    tags: Optional[List[str]] = None,
    privacy_status: str = "private",
    schedule_time: Optional[str] = None,
    schedule_mode: str = "local",
    thumbnail_path: Optional[str] = None
) -> Dict[str, Any]:
    """
    Queue or immediately upload a generated course video to YouTube.
    """
    rec = get_job(job_id)
    if not rec:
        raise ValueError(f"Job {job_id} not found.")

    video_path_str = rec.files.get("final_video") or (rec.files.get("videos", [None])[0] if isinstance(rec.files.get("videos"), list) else None)
    if not video_path_str:
        raise ValueError(f"Job {job_id} does not have a final video output.")

    video_path = Path(video_path_str)
    if not video_path.exists():
        raise FileNotFoundError(f"Video file not found at: {video_path}")

    # Auto-extract thumbnail if not provided
    if not thumbnail_path or not Path(thumbnail_path).exists():
        thumbnail_path = extract_video_thumbnail(str(video_path))

    # Auto-generate metadata if not provided
    if not title or not description:
        script_text = ""
        keywords_text = ""
        for k in ["script", "moneyprinter_video_script.txt"]:
            if k in rec.files and Path(rec.files[k]).exists():
                script_text = Path(rec.files[k]).read_text(encoding="utf-8")
                break
        for k in ["keywords", "moneyprinter_keywords.txt"]:
            if k in rec.files and Path(rec.files[k]).exists():
                keywords_text = Path(rec.files[k]).read_text(encoding="utf-8")
                break

        optimized = optimize_metadata(
            topic=rec.request.topic or "AutoCourse Video",
            script=script_text,
            keywords=keywords_text or rec.request.notes or "",
            visual_style=rec.request.visual_style.value if hasattr(rec.request.visual_style, "value") else str(rec.request.visual_style),
            video_path=str(video_path)
        )
        title = title or (optimized.titles[0] if optimized.titles else rec.request.topic)
        description = description or optimized.description
        tags = tags or optimized.tags

    is_immediate = (privacy_status != "scheduled") and (schedule_time is None)

    scheduled_rec = schedule_upload(
        video_path=str(video_path),
        title=title or rec.request.topic or "AutoCourse Video",
        description=description or "Generated by AutoCourse Studio",
        tags=tags or ["AutoCourse", "Education"],
        category_id="27",
        privacy_status=privacy_status,
        schedule_time=schedule_time,
        schedule_mode=schedule_mode,
        thumbnail_path=thumbnail_path,
        job_id=job_id,
        immediate=is_immediate
    )

    return {
        "success": True,
        "message": "Upload queued successfully" if not is_immediate else "Upload started",
        "schedule_id": scheduled_rec.schedule_id,
        "status": scheduled_rec.status
    }


def get_all_analytics() -> Dict[str, Any]:
    """
    Fetch comprehensive analytics including channel overview and metrics for all published videos.
    """
    channel_info = get_channel_profile()

    jobs = list_jobs()
    uploaded_jobs = [j for j in jobs.values() if j.get("youtube_video_id")]

    # Also check scheduled uploads queue for completed uploads
    from backend.services.youtube_scheduler import list_scheduled
    scheduled_items = list_scheduled()
    for s in scheduled_items:
        if s.get("youtube_video_id") and s.get("status") == "completed":
            if not any(j.get("youtube_video_id") == s["youtube_video_id"] for j in uploaded_jobs):
                uploaded_jobs.append({
                    "job_id": s.get("job_id") or s.get("schedule_id"),
                    "youtube_video_id": s.get("youtube_video_id"),
                    "request": {"topic": s.get("title", "Video")},
                    "uploaded_at": s.get("uploaded_at")
                })

    if not is_authenticated() or not uploaded_jobs:
        return {
            "channel": channel_info.get("channel"),
            "connected": is_authenticated(),
            "total_views": 0,
            "total_likes": 0,
            "total_comments": 0,
            "analytics": []
        }

    try:
        youtube = get_authenticated_service()
        video_ids = [j["youtube_video_id"] for j in uploaded_jobs]
        all_stats = []

        total_views = 0
        total_likes = 0
        total_comments = 0

        # Query YouTube API in batches of 50
        for i in range(0, len(video_ids), 50):
            batch = video_ids[i:i + 50]
            request = youtube.videos().list(
                part="snippet,statistics,contentDetails",
                id=",".join(batch)
            )
            response = request.execute()

            for item in response.get("items", []):
                vid_id = item["id"]
                snippet = item.get("snippet", {})
                stats = item.get("statistics", {})
                thumbs = snippet.get("thumbnails", {})

                thumb_url = (
                    thumbs.get("medium", {}).get("url")
                    or thumbs.get("default", {}).get("url")
                    or f"https://img.youtube.com/vi/{vid_id}/mqdefault.jpg"
                )

                views = int(stats.get("viewCount", 0))
                likes = int(stats.get("likeCount", 0))
                comments = int(stats.get("commentCount", 0))

                total_views += views
                total_likes += likes
                total_comments += comments

                # Find job
                job_for_vid = next((j for j in uploaded_jobs if j.get("youtube_video_id") == vid_id), {})

                all_stats.append({
                    "job_id": job_for_vid.get("job_id", ""),
                    "video_id": vid_id,
                    "title": snippet.get("title") or job_for_vid.get("request", {}).get("topic", "AutoCourse Video"),
                    "topic": job_for_vid.get("request", {}).get("topic", snippet.get("title", "Video")),
                    "description": snippet.get("description", ""),
                    "thumbnail_url": thumb_url,
                    "views": views,
                    "likes": likes,
                    "comments": comments,
                    "published_at": snippet.get("publishedAt", job_for_vid.get("uploaded_at")),
                    "watch_url": f"https://www.youtube.com/watch?v={vid_id}"
                })

        return {
            "channel": channel_info.get("channel"),
            "connected": True,
            "total_views": total_views,
            "total_likes": total_likes,
            "total_comments": total_comments,
            "analytics": all_stats
        }

    except Exception as e:
        print(f"[YouTubeUpload] Analytics error: {e}")
        return {
            "channel": channel_info.get("channel"),
            "connected": is_authenticated(),
            "error": str(e),
            "analytics": []
        }


def get_video_comments(video_id: str, max_results: int = 15) -> List[Dict[str, Any]]:
    """
    Fetch top viewer comments for a video via YouTube Data API v3.
    Used by the Autonomous Channel Director to analyze audience sentiment,
    feedback, and requested topics.
    """
    if not is_authenticated() or not video_id:
        return []
    try:
        youtube = get_authenticated_service()
        response = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=min(max_results, 50),
            order="relevance",
            textFormat="plainText"
        ).execute()

        comments = []
        for item in response.get("items", []):
            top = item.get("snippet", {}).get("topLevelComment", {}).get("snippet", {})
            comments.append({
                "author": top.get("authorDisplayName", "Viewer"),
                "text": top.get("textDisplay", ""),
                "like_count": int(top.get("likeCount", 0)),
                "published_at": top.get("publishedAt", "")
            })
        return comments
    except Exception as e:
        print(f"[YouTubeUpload] Could not fetch comments for video {video_id}: {e}")
        return []


def post_video_comment(video_id: str, text: str) -> Optional[str]:
    """Post an official channel comment (e.g. pinned discussion prompt)."""
    if not is_authenticated() or not video_id or not text:
        return None
    try:
        youtube = get_authenticated_service()
        response = youtube.commentThreads().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "topLevelComment": {
                        "snippet": {
                            "textOriginal": text
                        }
                    }
                }
            }
        ).execute()
        return response.get("id")
    except Exception as e:
        print(f"[YouTubeUpload] Could not post comment to video {video_id}: {e}")
        return None


def fetch_trending_niche_topics(query: str = "software engineering tutorial", max_results: int = 8) -> List[Dict[str, Any]]:
    """Fetch high-velocity trending search topics in the channel's niche."""
    if not is_authenticated():
        return []
    try:
        youtube = get_authenticated_service()
        cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7)).isoformat()
        res = youtube.search().list(
            part="snippet",
            q=query,
            type="video",
            order="viewCount",
            publishedAfter=cutoff,
            maxResults=min(max_results, 25)
        ).execute()
        trends = []
        for item in res.get("items", []):
            snippet = item.get("snippet", {})
            trends.append({
                "title": snippet.get("title", ""),
                "description": snippet.get("description", ""),
                "channel": snippet.get("channelTitle", "")
            })
        return trends
    except Exception as e:
        print(f"[YouTubeUpload] Trending search error: {e}")
        return []

